account_management_app/urls.py
from django.urls import path
from . import views

app_name = 'account_management_app'

urlpatterns = [
    path('', views.index, name="index"),
    path('transfer/<int:account_number>/', views.transfer, name="transfer"),
    path('my-profile/', views.my_profile, name="my_profile"),
    path('account_details/<int:account_number>/', views.account_details, name="account_details"),
    path('loan/<int:account_number>/', views.loan, name="loan"),
    path('loan/<int:account_number>/pay/', views.pay_back_loan, name="pay_back_loan"),

]

kea_bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login_app.urls')),
    path('', include('account_management_app.urls')),
    path('bank/', include('employee_app.urls')),

]

account_management_app/models.py
import uuid
from django.db import models, transaction
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models import Sum


class Customer(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10)

    class CustomerRank(models.TextChoices):
        BASIC = 'basic'
        SILVER = 'silver'
        GOLD = 'gold'

    rank = models.CharField(
        max_length=10,
        choices=CustomerRank.choices,
        default=CustomerRank.BASIC
    )

    @property
    def total_balance(self):
        accounts = Account.objects.filter(user=self.user)
        total_balance = 0
        for item in accounts:
            total_balance += item.balance
        return total_balance


class Account(models.Model):
    account_number = models.AutoField(primary_key=True)
    is_customer = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    class AccountType(models.TextChoices):
        PRIVATE = 'private'
        BUSINESS = 'business'
        LOAN = 'loan'

    account_type = models.CharField(
        max_length=10,
        choices=AccountType.choices,
        default=AccountType.PRIVATE
    )

    def get_transactions(self):
        my_transactions = Ledger.objects.filter(account=self)
        return my_transactions

    def get_loan_transactions(self):
        loan_transactions = Ledger.objects.filter(account=self, is_loan=True)
        return loan_transactions

    def get_amount_owed(self):
        loan_transactions = self.get_loan_transactions()
        if loan_transactions.count() == 0:
            return 0
        my_loan_transactions_with_balance = loan_transactions.aggregate(balance=Sum("amount"))
        return my_loan_transactions_with_balance['balance']

    @property
    def balance(self):
        my_transactions = self.get_transactions()
        if my_transactions.count() == 0:
            return 0
        my_transactions_with_balance = my_transactions.aggregate(balance=Sum("amount"))
        return my_transactions_with_balance['balance']

    def make_payment(self, amount, account_number, is_loan=False):
        if amount < 0:
            raise ValidationError('Please use a positive amount')
        if is_loan == False and self.balance < int(amount):
            raise ValidationError('Balance is too low')

        target_account = Account.objects.get(account_number=account_number)

        with transaction.atomic():
            transaction_id = uuid.uuid4()
            Ledger.objects.create(account=target_account, is_creditor=True, amount=int(amount), transaction_id=transaction_id, is_loan=is_loan, note='', variable_symbol='')
            Ledger.objects.create(account=self, is_creditor=False, amount=-int(amount), transaction_id=transaction_id, note='', is_loan=is_loan, variable_symbol='')


class Ledger(models.Model):

    transaction_id = models.UUIDField(default=uuid.uuid4, editable=False)
    account = models.ForeignKey(Account, on_delete=models.PROTECT)
    is_creditor = models.BooleanField(default=False)
    is_loan = models.BooleanField(default=False)
    amount = models.DecimalField(max_digits=15, decimal_places=4)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    note = models.CharField(max_length=100)
    variable_symbol = models.CharField(max_length=30)

    class Meta:
        unique_together = ['transaction_id', 'account']

account_management_app/views.py
from decimal import Decimal
from django.shortcuts import render
from . models import Account
from django.contrib.auth.decorators import login_required

from . models import Customer


@login_required(login_url='login_app:login')
def index(request):
    try:
        user = request.user
        accounts = Account.objects.filter(user=user)
        total_balance = user.customer.total_balance

        return render(request, 'account_management_app/index.html', {
            'accounts': accounts,
            'customer': user,
            'total_balance': total_balance
        })
    except Customer.DoesNotExist:
        return render(request, 'login_app/login.html', {})


def make_loan(request, account_number, pay_back=False):
    try:
        customer = request.user.customer
        my_account = Account.objects.get(account_number=account_number)
        amount_owed = my_account.get_amount_owed()
        loan_transactions = my_account.get_loan_transactions()

        if request.method == 'POST':
            if customer.rank == "basic":
                print('Cant apply for loan. Please upgrade your user rank.')
            amount = Decimal(request.POST['amount'])
            # gets banks operational account
            our_account = Account.objects.filter(is_customer=False)[0]
            if pay_back:
                if amount_owed >= amount:
                    my_account.make_payment(amount, our_account.account_number, is_loan=True)
                else:
                    # TODO: display error message
                    print('Cant return more than what you owe')
            else:
                our_account.make_payment(amount, account_number, is_loan=True)
            transactions = my_account.get_transactions
            return render(request, 'account_management_app/account_details.html', {
                'account': my_account,
                'transactions': transactions,
                'amount_owed': amount_owed,
                'loan_transactions': loan_transactions
            })
        else:
            return render(request, 'account_management_app/loan.html', {
                'account_number': account_number,
                'customer': customer,
                'amount_owed': amount_owed,
                'loan_transactions': loan_transactions
            })
    except Customer.DoesNotExist:
        return render(request, 'login_app/login.html', {})


@login_required(login_url='login_app:login')
def loan(request, account_number):
    try:
        return make_loan(request, account_number=account_number)
    except Customer.DoesNotExist:
        return render(request, 'login_app/login.html', {})


@login_required(login_url='login_app:login')
def pay_back_loan(request, account_number):
    try:
        return make_loan(request, account_number=account_number, pay_back=True)

    except Customer.DoesNotExist:
        return render(request, 'login_app/login.html', {})


@login_required(login_url='login_app:login')
def transfer(request, account_number):
    try:
        customer = request.user.customer
        my_account = Account.objects.get(account_number=account_number)
        accounts = Account.objects.filter(user=request.user)

        try:
            my_account.make_payment(Decimal(request.POST['amount']), request.POST['account_number'])
        except Exception as e:
            context['error'] = f'there was an error: {e}'

        context = {
            'accounts': accounts,
            'total_balance': customer.total_balance
        }
        return render(request, 'account_management_app/index.html', context)
    except Customer.DoesNotExist:
        return render(request, 'login_app/login.html', {})


@login_required(login_url='login_app:login')
def account_details(request, account_number):
    try:
        account = Account.objects.get(account_number=account_number)
        transactions = account.get_transactions

        return render(request, 'account_management_app/account_details.html', {
            'account': account,
            'transactions': transactions
        })
    except Customer.DoesNotExist:
        return render(request, 'login_app/login.html', {})


@login_required(login_url='/accounts/login/')
def my_profile(request):
    try:
        user = request.user
        return render(request, 'account_management_app/my_profile.html', {
            'customer': user.customer,
            'user': user
        })
    except Customer.DoesNotExist:
        return render(request, 'login_app/login.html', {})

account_management_app/templates/account_management_app/account_details.html
<div class="modal-content">
    <div id="account_{{account.account_number}}">
        <section class="col-element">
            <div class="top-details">
                <p>{{account.account_number}}</p>
                <a href="/">Close</a>
            </div>
        </section>
        <section class="popup-wrapper">
            <div class="transfering-wrapper">
                <h3>Transfering money</h3>
                <div class="balance">
                    <p>Balance: {{account.balance}} </p>
                </div>
                <div class="sending-money">
                    <form action="{% url 'account_management_app:transfer' account.account_number %}" method="post">
                        {% csrf_token %}
                        <input name="amount" type="number" placeholder="Amount" />
                        <input name="account_number" type="text" placeholder="Account number" />
                        <input name="note" type="text" placeholder="Note" />
                        <button>
                            Send
                        </button>
                    </form>
                </div>
                <hr />
                <h3>All transactions</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Amount</th>
                            <th>Note</th>
                        </tr>
                    </thead>
                    {% for transaction in transactions%}
                    <tbody>
                        <tr>
                            <td>{{transaction.created_timestamp}}</td>
                            <td>{{transaction.amount}}</td>
                            <td>{{transaction.note}}</td>
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
            <section class="col-element">
                <h3>Loan</h3>
                <div id="loan_container" hx-swap="outerHTML"
                    hx-get="{% url 'account_management_app:loan' account_number=account.account_number %}"
                    hx-trigger="load">
                </div>
            </section>
        </section>
    </div>
</div>

account_management_app/templates/account_management_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" media="all" />
    <script src="https://unpkg.com/htmx.org@1.8.0" defer></script>
    <title>Bank</title>
</head>

<body>
    <main>
        <div class="navigation">
            <a href="/">
                <img id="logo" src="{% static 'images/logo.png' %}" alt="Logo"/>
            </a>
            <nav>
                <a id="nav" href="/">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/dashboard.png' %}" alt="dashboard" />
                        <p>Dashboard</p>
                    </div>
                </a>
                <a id="nav" href="{% url 'account_management_app:my_profile' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/user.png' %}" alt="profile" />
                        <p>My profile</p>
                    </div>
                </a>
                <a id="nav" href="/">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/logout.png' %}" alt="profile" />
                        <p>Sign out</p>
                    </div>
                </a>
            </nav>
        </div>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </main>
</body>

</html>

account_management_app/templates/account_management_app/index.html
{% extends "account_management_app/base.html" %}
{% block content %}

<div class="account-wrapper">
    <h1>Dashboard</h1>
    <p> Welcome {{customer}} !</p>

    <div class="total-balance">
        <p>YOUR TOTAL BALANCE</p>

        <p id="amount_balance">{{total_balance}}</p>
    </div>

    <div class="payment-list">
        <div class="accounts">
            <h2>Your accounts</h2>
            {% for account in accounts %}

            <div class="account_number" id="{{account.account_number }}" class="clickable"
                hx-get="{% url 'account_management_app:account_details' account.account_number %}" hx-trigger="click"
                hx-target="this" hx-swap="outerHTML">
                <div>{{account.account_number}}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% if error %}
    {{ error }}
    {% endif %}
</div>
{% endblock %}

account_management_app/templates/account_management_app/loan.html
<div id="loan">
    {% if customer.rank == "basic" %}
    <p>You cant make a loan</p>

    {% else %}

    <p>Take loan money</p>
    <form>
        {% csrf_token %}
        <input type="number" name="amount" placeholder="Amount" />
        <button hx-post="{% url 'account_management_app:loan' account_number=account_number %}" hx-trigger="click"
            hx-target="#account_{{account_number}}" hx-swap="outerHTML">
            Take loan
        </button>
    </form>
    <hr />

    <p>Amount you have to return: {{amount_owed}}</p>
    <form>
        {% csrf_token %}
        <input type="number" name="amount" placeholder="Amount" />
        <button hx-post="{% url 'account_management_app:pay_back_loan' account_number=account_number %}"
            hx-trigger="click" hx-target="#account_{{account_number}}" hx-swap="outerHTML">
            Pay back
        </button>
    </form>
    <hr />
    {% endif %}

    <h3>Your loan history </h3>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Amount</th>
            </tr>
        </thead>
        {% for transaction in loan_transactions %}
        <tbody>
            <tr>
                <td>{{transaction.created_timestamp}}</td>
                <td>{{transaction.amount}}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
</div>

account_management_app/templates/account_management_app/my_profile.html
{% extends "account_management_app/base.html" %}
{% block content %}

<div>
    <h1 class="heading">My profile</h1>
    <div>
        <p>First name: {{user.first_name}}</p>

        <p>Last name: {{user.last_name}}</p>

        <p>Phone number: {{customer.phone_number}}</p>
        <p>Rank: {{customer.rank}}</p>
    </div>
</div>
{% endblock %}