employee_app/urls.py
from django.urls import path
from . import views

app_name = 'employee_app'

urlpatterns = [
    path('', views.index, name="index"),
    path('all-customers/', views.all_customers, name="all_customers"),
    path('customer/<int:pk>/', views.customer_detail, name="customer_detail"),
    path('my-profile/', views.my_profile, name="my_profile"),
    path('create-customer/', views.create_customer, name="create_customer"),
    path('account_detail/<int:account_number>/', views.account_detail, name="account_detail"),
    path('create-account/<int:pk>', views.create_account, name="create_account")
]

kea_bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login_app.urls')),
    path('', include('account_management_app.urls')),
    path('bank/', include('employee_app.urls')),

]

employee_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

employee_app/views.py
from django.shortcuts import render
from django.http import Http404
from django.contrib.auth.decorators import login_required


from account_management_app.models import Customer
from account_management_app.models import Account


@login_required(login_url='login_app:login')
def index(request):
    if hasattr(request.user, 'employee'):
        try:
            return render(request, 'employee_app/index.html', {})
        except Customer.DoesNotExist:
            return render(request, 'login_app/login.html', {})
    else:
        return render(request, 'login_app/login.html', {})


@login_required(login_url='login_app:login')
def all_customers(request):
    if hasattr(request.user, 'employee'):
        try:
            customers = Customer.objects.all()
            context = {
                'customers': customers,
            }

            return render(request, 'employee_app/all_customers.html', context)
        except Customer.DoesNotExist:
            return render(request, 'login_app/login.html', {})
    else:
        return render(request, 'login_app/login.html', {})


@login_required(login_url='login_app:login')
def my_profile(request):
    if hasattr(request.user, 'employee'):
        try:
            return render(request, 'employee_app/index.html', {})
        except Customer.DoesNotExist:
            return render(request, 'login_app/login.html', {})
    else:
        return render(request, 'login_app/login.html', {})


@login_required(login_url='login_app:login')
def account_detail(request, account_number):
    if hasattr(request.user, 'employee'):
        try:
            account = Account.objects.get(account_number=account_number)
            transactions = account.get_transactions

            context = {
                'account': account,
                'transactions': transactions
            }
            return render(request, 'employee_app/account_detail.html', context)

        except Customer.DoesNotExist:
            return render(request, 'login_app/login.html', {})
    else:
        return render(request, 'login_app/login.html', {})


@login_required(login_url='login_app:login')
def create_customer(request):
    if hasattr(request.user, 'employee'):
        try:
            return render(request, 'employee_app/index.html', {})

        except Customer.DoesNotExist:
            return render(request, 'login_app/login.html', {})
    else:
        return render(request, 'login_app/login.html', {})


@login_required(login_url='login_app:login')
def customer_detail(request, pk):
    if hasattr(request.user, 'employee'):
        try:
            customer = Customer.objects.get(pk=pk)
            accounts = Account.objects.filter(user=customer.user)
            context = {
                'customer': customer,
                'accounts': accounts,
            }
            return render(request, 'employee_app/customer_detail.html', context)

        except Customer.DoesNotExist:
            raise Http404("Customer does not exist")

    else:
        return render(request, 'login_app/login.html', {})


@login_required(login_url='login_app:login')
def create_account(request, pk):
    if hasattr(request.user, 'employee'):
        if request.method == "POST":
            customer = Customer.objects.get(pk=pk)
            account = Account(user=customer.user)
            account.save()
            context = {
                'customer': customer,
                'success': 'Account created'
            }
        else:
            context = {
                'error': 'Something went wrong'
            }
        return render(request, 'employee_app/create_account.html', context)
    else:
        return render(request, 'login_app/login.html', {})

employee_app/templates/employee_app/account_detail.html
{% extends "employee_app/base.html" %}
{% block content %}
<div clas="account-details">
    <h2>Account detail</h2>
    <p>Account number: {{account.account_number}}</p>
    <p>Balance: {{account.balance}} </p>
</div>
<div class="transaction">
    <h3>Transactions</h3>
    <table>
        <thead>
            <tr>

                <th>Date</th>
                <th>Amount</th>
                <th>Note</th>

            </tr>
        </thead>
        {% for transaction in transactions%}

        <tbody>
            <tr>
                <td>{{transaction.created_timestamp}}</td>
                <td>{{transaction.amount}}</td>
                <td>{{transaction.note}}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
</div>
{% endblock %}

employee_app/templates/employee_app/all_customers.html
{% extends "employee_app/base.html" %}
{% block content %}

<h1>All customers</h1>
{% for customer in customers %}
<div class="user-wrapper-link">
    <a href="{% url 'employee_app:customer_detail' pk=customer.pk %}">
        {{customer.user.username}}
    </a>
</div>
{% endfor %}
{% endblock %}

employee_app/templates/employee_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" media="all" />
    <script src="https://unpkg.com/htmx.org@1.8.0" defer></script>
    <title>Employee</title>
</head>

<body>
    <main>
        <div class="navigation">
            <a href="/">
                <img id="logo" src="{% static 'images/logo.png' %}" alt="Logo" />
            </a>
            <nav>
                <a id="nav" href="/bank">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/dashboard.png' %}" alt="dashboard" />
                        <p>Dashboard</p>
                    </div>
                </a>
                <a id="nav" href="{% url 'employee_app:all_customers' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/user.png' %}" alt="profile" />
                        <p>View all customers</p>
                    </div>
                </a>
                <a id="nav" href="{% url 'employee_app:create_customer' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/user.png' %}" alt="profile" />
                        <p>Create customer </p>
                    </div>
                </a>
                <a id="nav" href="{% url 'employee_app:my_profile' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/user.png' %}" alt="profile" />
                        <p>My profile</p>
                    </div>
                </a>
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/logout.png' %}" alt="profile" />
                        <p>Sign out</p>
                    </div>

            </nav>
        </div>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </main>
</body>

</html>

employee_app/templates/employee_app/create_account.html
{% extends "employee_app/base.html" %}
{% block content %}
<p>Account was successfully created</p>
{% endblock %}

employee_app/templates/employee_app/customer_detail.html
{% extends "employee_app/base.html" %}
{% block content %}
<h2>Customer detail</h2>
<div class="customer-info">
    <p>Username: {{customer.user.username}}</p>
    <p>First name: {{customer.user.first_name}}</p>
    <p>Last name: {{customer.user.last_name}}</p>
    <p>Email: {{customer.user.email}}</p>
    <p>Rank: {{customer.user.rank}}</p>
</div>
<div class="accounts">
    <h3>Accounts</h3>
    <form action="{% url 'employee_app:create_account' pk=customer.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Create account" />
    </form>
    <div class="account-wrapper">
        {% for account in accounts %}
        <a href="{% url 'employee_app:account_detail' account_number=account.account_number  %}">
            {{account.account_number}}
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

employee_app/templates/employee_app/index.html
{% extends "employee_app/base.html" %}
{% block content %}

<div>
    <h1>Dashboard for employees</h1>
</div>
{% endblock%}