kea_bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login_app.urls')),
    path('', include('account_management_app.urls')),
    path('bank/', include('employee_app.urls')),

]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),


]

login_app/models.py
# Create your models here.

login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth import authenticate, login as dj_login
from django.http import HttpResponseRedirect


def login(request):
    context = {}
    if request.method == "POST":
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        username = request.POST['username']
        if user:
            if username == 'employee':
                dj_login(request, user)
                return HttpResponseRedirect(reverse('employee_app:index'))
            else:
                dj_login(request, user)
                return HttpResponseRedirect(reverse('account_management_app:index'))
    else:
        context = {
            'error': 'Bad username or password.'
        }
    return render(request, 'login_app/login.html', context)

login_app/templates/login_app/login.html
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <title>Login</title>
</head>

<body>
   <h1>Login</h1>
   <hr />
   <form action="{% url 'login_app:login' %}" method="post">
      {% csrf_token %}
      <input type="text" name="username" placeholder="User Name" />
      <input type="password" name="password" placeholder="Password" />
      <button>Login</button>
   </form>
   <hr />
   {% if error %}
   {{ error }}
   {% endif %}
</body>

</html>